version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "3000:80"
    volumes:
      - .:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=matching_system
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
